image: samueldebruyn/debian-git

pipelines:
  default:
    - step:
        script:
          - echo "Everything is awesome!"
  branches:
    master:
    - step:
        script:
          - apt-get init
          - apt-get -qq install git-ftp

          - git ftp init --user $FTP_USERNAME --passwd $FTP_PASSWORD $FTP_CONNECTION

          - curl https://{{domain}}/?fwreinit=$FW_REINIT
